x-docusaurus-volumes: &docusaurus-volumes
  - ../doc:/app/docs
  - ./docusaurus.config.ts:/app/docusaurus.config.ts
  - ./sidebars.ts:/app/sidebars.ts
  - ./i18n:/app/i18n
  - ./src:/app/src
  - ./static:/app/static
  - ./versioned_docs:/app/versioned_docs
  - ./versioned_sidebars:/app/versioned_sidebars
  - ./versions.json:/app/versions.json
  - ./package.json:/app/package.json

services:
  docusaurus:
    build:
      context: .
      dockerfile: Dockerfile.docusaurus
    container_name: docusaurus-docs
    ports:
      - "3000:3000"
    volumes: *docusaurus-volumes

  docusaurus-prod:
    profiles: ["prod"]
    build:
      context: .
      dockerfile: Dockerfile.docusaurus
    container_name: docusaurus-prod
    command: sh -c "npm run build && npm run serve -- --host 0.0.0.0 --port 3000"
    ports:
      - "3001:3000"
    volumes: *docusaurus-volumes
