# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/variables.json
Variables:
  AI:
    # [enum: OpenAI, AzureOpenAI, Gemini, xAI, Anthropic]
    DefaultProvider: ""
    # Guardrails designed to ensure that AI operate safely ethical, and legal
    Guardrails:
      # Default input guardrails. Separated by comma. Example: "PromptInjectionInputGuardrail, GuardrailTwo"
      DefaultInput: ""
      # Default output guardrails. Separated by comma. Example: "SensitiveDataOutputGuardrail, GuardrailTwo"
      DefaultOutput: ""
    Tool:
      WebSearch:
        # Name of the search engine to use. Must match the name() of a registered SmartWebSearchEngine. Example: "duckduckgo"
        Engine: "duckduckgo"
        # Maximum number of search results returned per query.
        MaxResults: ""
        # Whitelist of allowed domains for web search results. Separated by comma. Example: "stackoverflow.com, github.com, docs.oracle.com"
        # If empty, all domains are allowed.
        WhitelistDomains: ""
    Observability:
      CustomFields:
        # Enable marking of workflow custom fields to track AI usage provenance.
        Enabled: "true"
      Ivy:
        # Enable chat history recording for governance audit.
        Enabled: ""
      Openinference:
        # Enable logging of AI interactions for observability and debugging purposes.
        Enabled: ""
        HideInputMessages: ""
        HideOutputMessages: ""
