# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/variables.json
Variables:
  AI:
    # [enum: OpenAI, AzureOpenAI, Gemini]
    DefaultProvider: ""
    # Guardrails designed to ensure that AI operate safely ethical, and legal
    Guardrails:
      # Default input guardrails. Separated by comma. Example: "PromptInjectionInputGuardrail, GuardrailTwo"
      DefaultInput: ""
    Observability:
      Ivy:
        # Enable chat history recording for governance audit.
        Enabled: false
