#
# OpenTelemetry Java agent configuration file
#
otel.traces.exporter=otlp
otel.metrics.exporter=none
otel.logs.exporter=none
# Openinference AI project
otel.resource.attributes=openinference.project.name=smart-workflow
# The host and port where to report tracings to the Arize Phoenix tracing tool
otel.exporter.otlp.endpoint=http://127.0.0.1:6006
otel.propagators=jaeger

